name: lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: modules
        run: go mod download
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
