name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go
      - name: checkout
        uses: actions/checkout@v2
      - name: modules
        run: go mod download
      - name: test
        run: go test -v ./...
